line-length = 88

src = [
  "src",
  "tests",
  "docs",
  "setup.py",
]
extend-exclude = [
  "docs",
  "scripts/strun",
]

[lint]
select = [
  "S",  # flake8-bandit
  "I",  # isort
  "E",  # pycodestyle
  "W",  # pycodestyle
  "F",  # Pyflakes
  "UP",  # pyupgrade
]
extend-select = [
  "NPY",  # NumPy-specific checks (recommendations from NumPy)
]

[lint.extend-per-file-ignores]
"tests/*" = [
  "S101",  # Use of `assert` detected
  "S603",
  "S607",
]
"src/stpipe/tests/*.py" = [
  "S101",
]
