name: Weekly CI

on:
  schedule:
    # Weekly Monday 6AM build
    - cron: "0 0 * * 1"
  pull_request:
    # We also want this workflow triggered if the `Weekly CI` label is
    # added or present when PR is updated
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    if: (github.repository == 'spacetelescope/stpipe' && (github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'Weekly CI')))
    with:
      envs: |
        - macos: py39-xdist
        - macos: py310-xdist
        - windows: py311-xdist
        - linux: py3-devdeps-xdist
        - macos: py3-devdeps-xdist
