name: confirm changelog entry

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: scientific-python/action-check-changelogfile@0.2
      env:
        CHANGELOG_FILENAME: CHANGES.rst
        CHECK_MILESTONE: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
