name: Publish to PyPI

on:
  release:
    types: [ released ]

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      targets: |
        - linux
        - macos
      sdist: true
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }}

